# Change these
owner: SocialGouv # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Fabrique
    url: https://fabrique.social.gouv.fr
  - name: Template
    url: https://template.fabrique.social.gouv.fr/
  - name: Index EgaPro
    url: http://egapro.travail.gouv.fr/
  - name: Code du travail
    url: https://code.travail.gouv.fr
  - name: siret2idcc
    url: https://siret2idcc.fabrique.social.gouv.fr/api/v2/82161143100015,80258570300027
  - name: serving-ml
    url: https://serving-ml.fabrique.social.gouv.fr/v1/models/sentqam
  - name: emjpm
    url: https://emjpm.fabrique.social.gouv.fr
  - name: portail PJM
    url: https://pjm.social.gouv.fr/
  - name: covid-19
    url: https://covid-19.sante.gouv.fr
  - name: TuMePlay
    url: https://tumeplay.fabrique.social.gouv.fr/
  - name: ONVS
    url: https://onvs.fabrique.social.gouv.fr/
  - name: DomiFa
    url: https://domifa.fabrique.social.gouv.fr/
  - name: Standup
    url: https://standup.fabrique.social.gouv.fr/healthz
  - name: Carnets
    url: https://carnets.fabrique.social.gouv.fr/api/healthz
  - name: Archifiltre
    url: https://archifiltre.fabrique.social.gouv.fr/
  - name: MonSuiviPsy
    url: https://monsuivipsy.fabrique.social.gouv.fr/
  - name: OzEnsemble
    url: https://ozensemble.fabrique.social.gouv.fr/
  - name: Enfants du spectacle
    url: https://enfants-du-spectacle.fabrique.social.gouv.fr/
  - name: Matomo
    url: https://matomo.fabrique.social.gouv.fr/
  - name: Sentry
    url: https://sentry.fabrique.social.gouv.fr/
  - name: Mattermost
    url: https://mattermost.fabrique.social.gouv.fr/
  - name: NextCloud
    url: https://nextcloud.fabrique.social.gouv.fr/
  - name: Sample Next App
    url: https://sample-next-app.fabrique.social.gouv.fr
  - name: GitLab
    url: https://gitlab.fabrique.social.gouv.fr

commitMessages:
  commitAuthorName: "Social Groovy Bot"
  commitAuthorEmail: "45039513+SocialGroovyBot@users.noreply.github.com"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://github.com/SocialGouv/support/raw/master/docs/_media/marianne-small.jpeg
  name: SocialGouv Uptime
  introTitle: "SocialGouv services status"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
